#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir/app" --full_replace --keep="sites"

#=================================================
# UPGRADE COMPOSER
#=================================================
ynh_script_progression "Upgrading Composer..."

ynh_composer_install
ynh_composer_exec install --no-dev

#=================================================
# UPGRADE DRUPAL
#=================================================
ynh_script_progression "Upgrading Drupal..."

ynh_backup_if_checksum_is_different "$install_dir/app/sites/default/settings.php"

# Chown from composer/drush install
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:www-data" "$install_dir"
pushd "$install_dir"
    _ynh_exec_with_drush_php drush "@$app" variable-set --exact maintenance_mode 1
    _ynh_exec_with_drush_php drush "@$app" cache-clear all
    # _ynh_exec_with_drush_php drush "@$app" pm-update -y drupal
    # _ynh_exec_with_drush_php drush "@$app" updatedb -y
    _ynh_exec_with_drush_php drush "@$app" cache-clear all
    _ynh_exec_with_drush_php drush "@$app" variable-set --exact maintenance_mode 0
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
